import {
  Smartphone,
  Headphones,
  Shirt,
  Footprints,
  Sparkles,
  ShoppingBasket,
  Utensils,
  Laptop,
  Lamp,
  PencilRuler,
  HeartPulse,
  Baby,
  ConciergeBell,
  Package2,
  BadgeCheck,
  type LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  smartphone: Smartphone,
  headphones: Headphones,
  shirt: Shirt,
  footprints: Footprints,
  sparkles: Sparkles,
  "shopping-basket": ShoppingBasket,
  utensils: Utensils,
  laptop: Laptop,
  lamp: Lamp,
  "pencil-ruler": PencilRuler,
  "heart-pulse": HeartPulse,
  baby: Baby,
  "concierge-bell": ConciergeBell,
  "package-2": Package2,
  "badge-check": BadgeCheck,
};
