import { notFound } from "next/navigation";
import Link from "next/link";
import type { Metadata } from "next";
import {
  Boxes,
  CalendarClock,
  Check,
  GraduationCap,
  MapPin,
  MessageCircle,
  Plane,
  ShieldCheck,
  Star,
  Store,
  Truck,
} from "lucide-react";
import { Container } from "@/components/ui/Container";
import { PageHeader } from "@/components/ui/PageHeader";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { ProductGrid } from "@/components/product/ProductGrid";
import { ProductGallery } from "@/components/product/ProductGallery";
import { AddToCartButton } from "@/components/cart/AddToCartButton";
import { ShareButton } from "@/components/share/ShareButton";
import { Badge } from "@/components/ui/Badge";
import {
  getCategories,
  getProductBySlug,
  getRelatedProducts,
  getVendorById,
  getVendorNameMap,
} from "@/lib/catalog";
import { discountPercent, formatPrice } from "@/lib/format";
import { countryByCode, estimatedArrival, isAbroad } from "@/lib/countries";
import { waChatLink } from "@/lib/whatsapp";
import { freightModeLabel, hasAnyTerms, isAbroadType, toAbroadTerms } from "@/lib/abroad";
import { describePoint } from "@/lib/shipping";
import { getConsolidationPoint, getForwarders, getLeadDays } from "@/lib/shipping-config";
import { productBadges } from "@/lib/product-badges";

type Params = Promise<{ slug: string }>;

export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> {
  const { slug } = await params;
  const product = await getProductBySlug(slug);
  if (!product) return { title: "Product — Nickimart" };

  const title = `${product.name} — Nickimart`;
  const description = (product.description?.trim() || "Shop this and more on Nickimart.").slice(0, 200);
  const url = `/products/${slug}`;
  // The product image itself is generated by opengraph-image.tsx and injected
  // automatically; here we set the title/description/url for the link preview.
  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: { title, description, url, type: "website", siteName: "Nickimart" },
    twitter: { card: "summary_large_image", title, description },
  };
}

export default async function ProductDetailPage({ params }: { params: Params }) {
  const { slug } = await params;
  const product = await getProductBySlug(slug);
  if (!product) notFound();

  // Only terms the seller actually wrote; null keeps the panel off entirely.
  const abroadTerms = product.preorderInfo ? toAbroadTerms(product.preorderInfo) : null;
  const shippedFromAbroad = isAbroadType(product.productType) && abroadTerms !== null;

  const [vendor, categories, related, vendorNames] = await Promise.all([
    getVendorById(product.vendorId),
    getCategories(),
    getRelatedProducts(product),
    getVendorNameMap(),
  ]);
  const category = categories.find((c) => c.id === product.categoryId);
  const discount = discountPercent(product.price, product.oldPrice);

  // The same derived list the cards use, so a listing marked as imported is
  // labelled here whether or not anyone typed the badge.
  const badges = productBadges(product);
  const abroad = shippedFromAbroad || isAbroad(product.originCountry);
  const originCountry = countryByCode(product.originCountry);
  const leadDays = abroad ? await getLeadDays(product.originCountry ?? "") : 0;
  const arrivalDate = abroad ? estimatedArrival(leadDays) : null;
  // Where this listing's goods gather, and who brings them in. Shown so a buyer
  // can see the journey — not the money behind it, which is one figure at
  // checkout and stays one figure.
  const consolidationPoint = shippedFromAbroad
    ? await getConsolidationPoint(abroadTerms.consolidationPointId || product.arrivalPointId)
    : null;
  const forwarder = shippedFromAbroad
    ? ((await getForwarders()).find(
        (f) => f.id === (abroadTerms.forwarderId || product.forwarderId),
      ) ?? null)
    : null;
  // The lane the seller listed this on: it carries the mode and the delivery
  // estimate the buyer is actually being promised.
  const freightRoute =
    forwarder?.routes.find(
      (r) => r.id === (abroadTerms?.routeId || product.forwarderRouteId),
    ) ?? null;

  const deliveryOptions = [
    product.sameDayDeliveryAvailable && { icon: Truck, label: "Same-day delivery available" },
    product.campusDeliveryAvailable && { icon: GraduationCap, label: "Campus delivery available" },
    product.pickupAvailable && { icon: MapPin, label: "Pickup available" },
  ].filter(Boolean) as { icon: typeof Truck; label: string }[];

  return (
    <>
      <PageHeader
        title={product.name}
        crumbs={[
          { label: "Products", href: "/products" },
          ...(category ? [{ label: category.name, href: `/categories/${category.slug}` }] : []),
          { label: product.name },
        ]}
      />

      <Container className="py-8">
        <div className="grid gap-8 lg:grid-cols-2">
          <div>
            <ProductGallery
              images={product.images ?? []}
              gradientFrom={product.gradientFrom}
              gradientTo={product.gradientTo}
              emoji={product.emoji}
              alt={product.name}
            />
            {badges.length > 0 ? (
              <div className="mt-3 flex flex-wrap gap-1.5">
                {badges.map((b) => (
                  <Badge key={b} kind={b} />
                ))}
              </div>
            ) : null}
          </div>

          <div>
            {vendor ? (
              <Link
                href={`/shops/${vendor.slug}`}
                className="inline-flex items-center gap-1.5 text-sm font-medium text-niki-orange hover:underline"
              >
                <Store className="h-4 w-4" />
                {vendor.businessName}
                {vendor.verificationStatus === "verified" ? (
                  <ShieldCheck className="h-4 w-4 text-niki-success" />
                ) : null}
              </Link>
            ) : null}
            {vendor?.whatsapp && waChatLink(vendor.whatsapp) ? (
              <a
                href={waChatLink(vendor.whatsapp, `Hi ${vendor.businessName}, I'm interested in "${product.name}" on Nickimart.`)!}
                target="_blank"
                rel="noopener noreferrer"
                className="ml-3 inline-flex items-center gap-1.5 text-sm font-semibold text-[#25D366] hover:underline"
              >
                <MessageCircle className="h-4 w-4" />
                Chat on WhatsApp
              </a>
            ) : null}

            <div className="mt-2 flex items-start justify-between gap-3">
              <h1 className="font-display text-2xl font-bold text-niki-ink sm:text-3xl">
                {product.name}
              </h1>
              <ShareButton path={`/products/${product.slug}`} title={product.name} label="" />
            </div>

            <div className="mt-3 flex items-center gap-2 text-sm text-niki-ink/60">
              <span className="flex items-center gap-1">
                <Star className="h-4 w-4 fill-niki-gold text-niki-gold" />
                <span className="font-semibold text-niki-ink">{product.rating.toFixed(1)}</span>
              </span>
              <span>({product.reviewCount} reviews)</span>
            </div>

            <div className="mt-5 flex items-baseline gap-3">
              <span className="font-figures text-3xl font-bold text-niki-ink">
                {formatPrice(product.price)}
              </span>
              {product.oldPrice ? (
                <span className="text-lg text-niki-ink/40 line-through">
                  {formatPrice(product.oldPrice)}
                </span>
              ) : null}
              {discount ? (
                <span className="rounded-full bg-niki-danger px-2 py-0.5 text-xs font-bold text-white">
                  -{discount}%
                </span>
              ) : null}
            </div>

            {(product.moq ?? 1) > 1 ? (
              // Beside the price, not buried in the description: the price of
              // one unit and a minimum of twelve are one fact, and a buyer who
              // meets the second of them at checkout feels misled by the first.
              <p className="mt-2 inline-flex items-center gap-1.5 rounded-full bg-niki-black/5 px-3 py-1 text-xs font-semibold text-niki-ink/70">
                <Boxes className="h-3.5 w-3.5 text-niki-orange" />
                Minimum order: {product.moq} units ·{" "}
                {formatPrice(product.price * (product.moq ?? 1))}
              </p>
            ) : null}

            <p className="mt-5 text-sm leading-relaxed text-niki-ink/70">{product.description}</p>

            {abroad && arrivalDate ? (
              <div className="mt-5 flex items-start gap-3 rounded-2xl bg-niki-trust/10 p-4 ring-1 ring-niki-trust/20">
                <Plane className="mt-0.5 h-5 w-5 shrink-0 text-niki-trust" />
                <div className="text-sm">
                  <p className="font-semibold text-niki-trust">
                    Shipped from abroad{originCountry ? ` · ${originCountry.flag} ${originCountry.name}` : ""}
                  </p>
                  <p className="mt-1 text-niki-ink/70">
                    Estimated arrival:{" "}
                    <span className="font-semibold text-niki-ink">
                      {arrivalDate.toLocaleDateString("en-GH", { day: "numeric", month: "long", year: "numeric" })}
                    </span>{" "}
                    <span className="text-niki-ink/50">(~{leadDays} days)</span>
                  </p>
                  <p className="mt-1 text-xs text-niki-ink/50">
                    Delivered to your door or pickup point once it clears customs.
                  </p>
                </div>
              </div>
            ) : null}

            {product.attributes && product.attributes.length > 0 ? (
              <div className="mt-6">
                <h2 className="font-display text-sm font-bold uppercase tracking-wide text-niki-ink/70">
                  Key attributes
                </h2>
                <div className="mt-2 overflow-hidden rounded-xl ring-1 ring-niki-edge">
                  <table className="w-full text-sm">
                    <tbody className="divide-y divide-niki-edge">
                      {product.attributes.map((attr, i) => (
                        <tr key={i} className={i % 2 === 0 ? "bg-white" : "bg-niki-surface"}>
                          <th className="w-2/5 px-4 py-2.5 text-left font-medium text-niki-ink/60">{attr.label}</th>
                          <td className="px-4 py-2.5 font-medium text-niki-ink">{attr.value}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            ) : null}

            {abroadTerms && hasAnyTerms(abroadTerms) ? (
              <div className="mt-5 rounded-2xl bg-niki-orange/[0.07] p-4 text-sm ring-1 ring-niki-orange/30">
                <p className="flex items-center gap-2 font-semibold text-niki-ink">
                  <CalendarClock className="h-4 w-4 text-niki-orange" />
                  Shipped from abroad — please review before ordering
                </p>
                {/* The facts, as a grid rather than a list of sentences: a
                    shopper scans this for four things — where from, how, when,
                    what it costs on top — and a paragraph makes them read to
                    find each one. Terms the seller left blank are dropped; a
                    labelled blank reads as a promise nobody made. */}
                <dl className="mt-3 grid gap-x-6 gap-y-2 sm:grid-cols-2">
                  <Fact label="Ships from" value={abroadTerms.sourceLocation} />
                  <Fact
                    label="Arrives"
                    value={abroadTerms.estimatedArrival || (leadDays ? `about ${leadDays} days` : "")}
                  />
                  <Fact label="Freight" value={freightModeLabel(freightRoute?.mode)} />
                  <Fact
                    label="Collected in Ghana at"
                    value={consolidationPoint ? describePoint(consolidationPoint) : ""}
                  />
                  <Fact
                    label="Shipping"
                    value={
                      product.shippingMethod === "free"
                        ? "Free to any pickup station"
                        : "One figure at checkout, for the station you choose"
                    }
                  />
                </dl>

                {abroadTerms.refundPolicy ? (
                  <p className="mt-3 text-xs leading-relaxed text-niki-ink/60">
                    {abroadTerms.refundPolicy}
                  </p>
                ) : null}

                <p className="mt-3 text-xs text-niki-ink/60">
                  Ordering never closes.{" "}
                  {product.shippingOnPickup
                    ? "You can pay for the item now and settle the shipping when you collect. "
                    : ""}
                  You&apos;ll see the price and the shipping to your station at checkout.
                  {abroadTerms.sourceUrl ? (
                    <>
                      {" "}
                      <a
                        href={abroadTerms.sourceUrl}
                        target="_blank"
                        rel="noopener noreferrer nofollow"
                        className="font-semibold text-niki-orange hover:underline"
                      >
                        View the supplier&apos;s listing
                      </a>
                    </>
                  ) : null}
                </p>
              </div>
            ) : null}

            {product.serviceInfo ? (
              <div className="mt-5 rounded-2xl bg-niki-surface p-4 text-sm ring-1 ring-niki-edge">
                <p className="font-semibold text-niki-ink">Service details</p>
                <ul className="mt-3 space-y-1.5 text-niki-ink/70">
                  <li>Service area: {product.serviceInfo.serviceArea}</li>
                  <li>Availability: {product.serviceInfo.availability}</li>
                  <li>{product.serviceInfo.bookingNotes}</li>
                </ul>
              </div>
            ) : null}

            {deliveryOptions.length > 0 ? (
              <div className="mt-5 space-y-2">
                {deliveryOptions.map((opt) => (
                  <p key={opt.label} className="flex items-center gap-2 text-sm text-niki-ink/70">
                    <opt.icon className="h-4 w-4 text-niki-success" />
                    {opt.label}
                  </p>
                ))}
              </div>
            ) : null}

            <div className="mt-7">
              <AddToCartButton
                addLabel={product.productType === "service" ? "Book service" : "Add to cart"}
                moq={product.moq ?? 1}
                item={{
                  productId: product.id,
                  slug: product.slug,
                  name: product.name,
                  price: product.price,
                  emoji: product.emoji,
                  gradientFrom: product.gradientFrom,
                  gradientTo: product.gradientTo,
                  image: product.image,
                  vendorId: product.vendorId,
                  weightKg: product.shippingWeightKg,
                  volumeCm3: (product.lengthCm || 0) * (product.widthCm || 0) * (product.heightCm || 0),
                  moq: product.moq ?? 1,
                }}
              />
            </div>

            <p className="mt-4 flex items-center gap-2 text-xs text-niki-ink/50">
              <Check className="h-3.5 w-3.5 text-niki-success" />
              Covered by Nickimart Buyer Protection
            </p>
          </div>
        </div>

        {related.length > 0 ? (
          <div className="mt-14">
            <SectionHeading title="You may also like" />
            <ProductGrid products={related} vendorNames={vendorNames} />
          </div>
        ) : null}
      </Container>
    </>
  );
}

/** One labelled fact in the shipped-from-abroad panel, or nothing at all. */
function Fact({ label, value }: { label: string; value: string }) {
  if (!value.trim()) return null;
  return (
    <div>
      <dt className="text-xs font-medium uppercase tracking-wide text-niki-ink/45">{label}</dt>
      <dd className="text-sm text-niki-ink/80">{value}</dd>
    </div>
  );
}
