/**
 * Generates a single, self-contained `nikimart-neon-setup.sql` that:
 *   1. drops any existing NikiMart tables (safe to re-run),
 *   2. creates the schema (from the Prisma migration),
 *   3. records the migration in `_prisma_migrations`,
 *   4. seeds demo accounts, catalog, pickup points, and sample orders.
 *
 * Intended to be pasted into the Neon SQL Editor (or `psql`) when a direct
 * Postgres connection isn't available. Run: `npx tsx scripts/generate-setup-sql.ts`
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";
import bcrypt from "bcryptjs";
import { categories, vendors, products } from "../src/lib/mock-data";

const MIGRATIONS_DIR = path.join(process.cwd(), "prisma", "migrations");
// All migrations, in chronological (name) order.
const migrations = readdirSync(MIGRATIONS_DIR)
  .filter((d) => /^\d+_/.test(d))
  .sort()
  .map((name) => {
    const file = path.join(MIGRATIONS_DIR, name, "migration.sql");
    const sql = readFileSync(file, "utf8");
    return { name, sql, checksum: createHash("sha256").update(readFileSync(file)).digest("hex") };
  });

// ---- helpers ---------------------------------------------------------------
const q = (v: string | null | undefined) =>
  v === null || v === undefined ? "NULL" : `'${v.replace(/'/g, "''")}'`;
const n = (v: number | null | undefined) => (v === null || v === undefined ? "NULL" : String(v));
const b = (v: boolean) => (v ? "TRUE" : "FALSE");
const j = (v: unknown) => q(JSON.stringify(v));

const TABLES = [
  "PageSection",
  "Page",
  "SiteSetting",
  "Shipment",
  "OrderItem",
  "Order",
  "PickupPoint",
  "Product",
  "Vendor",
  "Category",
  "Session",
  "Account",
  "VerificationToken",
  "User",
  "_prisma_migrations",
];

const out: string[] = [];
out.push("-- NikiMart — Neon setup script (schema + seed). Safe to re-run.");
out.push("-- Generated by scripts/generate-setup-sql.ts");
out.push("BEGIN;");
out.push("");
out.push("-- 1. Clean slate --------------------------------------------------------");
for (const t of TABLES) out.push(`DROP TABLE IF EXISTS "${t}" CASCADE;`);
out.push("");
out.push("-- 2. Schema (from all prisma migrations, in order) --------------------");
for (const m of migrations) {
  out.push(`-- migration: ${m.name}`);
  out.push(m.sql.trim());
  out.push("");
}
out.push("-- 3. Prisma migration bookkeeping --------------------------------------");
out.push(
  `CREATE TABLE IF NOT EXISTS "_prisma_migrations" (
  "id" VARCHAR(36) PRIMARY KEY NOT NULL,
  "checksum" VARCHAR(64) NOT NULL,
  "finished_at" TIMESTAMPTZ,
  "migration_name" VARCHAR(255) NOT NULL,
  "logs" TEXT,
  "rolled_back_at" TIMESTAMPTZ,
  "started_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "applied_steps_count" INTEGER NOT NULL DEFAULT 0
);`,
);
for (const m of migrations) {
  out.push(
    `INSERT INTO "_prisma_migrations" ("id","checksum","finished_at","migration_name","started_at","applied_steps_count")
VALUES ('${crypto.randomUUID()}', '${m.checksum}', now(), '${m.name}', now(), 1);`,
  );
}
out.push("");

// ---- 4. Seed ---------------------------------------------------------------
const passwordHash = bcrypt.hashSync("password123", 10);

const demoUsers = [
  { id: "usr-customer", email: "customer@nikimart.test", name: "Ama Mensah", role: "CUSTOMER", phone: "024 000 0001" },
  { id: "usr-seller", email: "seller@nikimart.test", name: "Kojo Owusu", role: "SELLER", phone: "024 000 0002" },
  { id: "usr-admin", email: "admin@nikimart.test", name: "Nana Adjei", role: "ADMIN", phone: "024 000 0003" },
  { id: "usr-freight", email: "freight@nikimart.test", name: "Yaw Boateng", role: "FREIGHT", phone: "024 000 0004" },
  { id: "usr-pickup", email: "pickup@nikimart.test", name: "Efua Sarpong", role: "PICKUP", phone: "024 000 0005" },
];

out.push("-- 4. Demo accounts (password for all: password123) --------------------");
for (const u of demoUsers) {
  out.push(
    `INSERT INTO "User" ("id","name","email","phone","passwordHash","role","createdAt","updatedAt") VALUES (${q(u.id)}, ${q(u.name)}, ${q(u.email)}, ${q(u.phone)}, ${q(passwordHash)}, ${q(u.role)}, now(), now());`,
  );
}
out.push("");

out.push("-- Categories ----------------------------------------------------------");
for (const c of categories) {
  out.push(
    `INSERT INTO "Category" ("id","name","slug","icon","description","productCount") VALUES (${q(c.id)}, ${q(c.name)}, ${q(c.slug)}, ${q(c.icon)}, ${q(c.description)}, ${n(c.productCount)});`,
  );
}
out.push("");

out.push("-- Vendors (first vendor owned by the seller demo account) -------------");
vendors.forEach((v, i) => {
  const ownerId = i === 0 ? "'usr-seller'" : "NULL";
  out.push(
    `INSERT INTO "Vendor" ("id","slug","businessName","sellerTypes","description","initials","accentFrom","accentTo","locationIds","verificationStatus","rating","reviewCount","totalSales","isOfficial","deliveryAvailable","pickupAvailable","sameDayDeliveryAvailable","ownerId") VALUES (${q(v.id)}, ${q(v.slug)}, ${q(v.businessName)}, ${j(v.sellerTypes)}, ${q(v.description)}, ${q(v.initials)}, ${q(v.accentFrom)}, ${q(v.accentTo)}, ${j(v.locationIds)}, ${q(v.verificationStatus)}, ${n(v.rating)}, ${n(v.reviewCount)}, ${n(v.totalSales)}, ${b(v.isOfficial)}, ${b(v.deliveryAvailable)}, ${b(v.pickupAvailable)}, ${b(v.sameDayDeliveryAvailable)}, ${ownerId});`,
  );
});
out.push("");

out.push("-- Products ------------------------------------------------------------");
for (const p of products) {
  out.push(
    `INSERT INTO "Product" ("id","slug","name","description","price","oldPrice","stockQuantity","productType","badges","locationIds","campusDeliveryAvailable","pickupAvailable","sameDayDeliveryAvailable","isOfficial","isFeatured","rating","reviewCount","gradientFrom","gradientTo","emoji","image","preorderInfo","serviceInfo","categoryId","vendorId") VALUES (${q(p.id)}, ${q(p.slug)}, ${q(p.name)}, ${q(p.description)}, ${n(p.price)}, ${n(p.oldPrice)}, ${n(p.stockQuantity)}, ${q(p.productType)}, ${j(p.badges)}, ${j(p.locationIds)}, ${b(p.campusDeliveryAvailable)}, ${b(p.pickupAvailable)}, ${b(p.sameDayDeliveryAvailable)}, ${b(p.isOfficial)}, ${b(p.isFeatured)}, ${n(p.rating)}, ${n(p.reviewCount)}, ${q(p.gradientFrom)}, ${q(p.gradientTo)}, ${q(p.emoji)}, ${q(p.image ?? `/products/${p.slug}.jpg`)}, ${p.preorderInfo ? j(p.preorderInfo) : "NULL"}, ${p.serviceInfo ? j(p.serviceInfo) : "NULL"}, ${q(p.categoryId)}, ${q(p.vendorId)});`,
  );
}
out.push("");

const pickupPoints = [
  { id: "pp-ug-legon", name: "NikiMart Pickup — Legon", code: "UG-LEGON", locationName: "University of Ghana, Legon", address: "Night Market, near the JQB block, Legon Campus", operatorId: "'usr-pickup'" },
  { id: "pp-knust", name: "NikiMart Pickup — KNUST", code: "KNUST-CENTRAL", locationName: "KNUST, Kumasi", address: "Commercial Area, opposite the Central Cafeteria", operatorId: "NULL" },
  { id: "pp-sunyani", name: "NikiMart Pickup — Sunyani", code: "SUNYANI-MAIN", locationName: "Sunyani Central", address: "Nana Bosoma Market Road, near the STC yard", operatorId: "NULL" },
];
out.push("-- Pickup points -------------------------------------------------------");
for (const pp of pickupPoints) {
  out.push(
    `INSERT INTO "PickupPoint" ("id","name","code","locationName","address","isActive","createdAt","operatorId") VALUES (${q(pp.id)}, ${q(pp.name)}, ${q(pp.code)}, ${q(pp.locationName)}, ${q(pp.address)}, TRUE, now(), ${pp.operatorId});`,
  );
}
out.push("");

const priceOf = new Map(products.map((p) => [p.id, p.price]));
const orders = [
  { id: "order-1001", num: "NM-1001", status: "delivered", method: "delivery", address: "Hall 6, Room 214, Legon Campus, Accra", pp: "NULL", items: [["prod-iphone13", 1], ["prod-earbuds", 1]], ship: { id: "ship-1001", tn: "NMF-1001", st: "delivered", from: "Accra Warehouse", to: "Legon Campus, Accra" } },
  { id: "order-1002", num: "NM-1002", status: "shipped", method: "pickup", address: null, pp: "'pp-ug-legon'", items: [["prod-powerbank", 2]], ship: { id: "ship-1002", tn: "NMF-1002", st: "in_transit", from: "Accra Warehouse", to: "NikiMart Pickup — Legon" } },
  { id: "order-1003", num: "NM-1003", status: "paid", method: "delivery", address: "Ahodwo, Kumasi", pp: "NULL", items: [["prod-skincare", 1]], ship: { id: "ship-1003", tn: "NMF-1003", st: "processing", from: "Kumasi Hub", to: "Ahodwo, Kumasi" } },
] as const;

out.push("-- Sample orders + items + shipments -----------------------------------");
for (const o of orders) {
  const lineItems = o.items.map(([pid, qty]) => ({ pid, qty: qty as number, price: priceOf.get(pid as string) ?? 0 }));
  const subtotal = lineItems.reduce((s, it) => s + it.price * it.qty, 0);
  const deliveryFee = o.method === "pickup" ? 0 : 20;
  const total = subtotal + deliveryFee;
  out.push(
    `INSERT INTO "Order" ("id","orderNumber","status","subtotal","deliveryFee","total","deliveryMethod","address","createdAt","updatedAt","userId","pickupPointId") VALUES (${q(o.id)}, ${q(o.num)}, ${q(o.status)}, ${n(subtotal)}, ${n(deliveryFee)}, ${n(total)}, ${q(o.method)}, ${q(o.address)}, now(), now(), 'usr-customer', ${o.pp});`,
  );
  lineItems.forEach((it, idx) => {
    out.push(
      `INSERT INTO "OrderItem" ("id","quantity","unitPrice","orderId","productId") VALUES (${q(o.id + "-i" + idx)}, ${n(it.qty)}, ${n(it.price)}, ${q(o.id)}, ${q(it.pid)});`,
    );
  });
  out.push(
    `INSERT INTO "Shipment" ("id","trackingNumber","status","carrier","origin","destination","eta","createdAt","updatedAt","orderId","freightAgentId") VALUES (${q(o.ship.id)}, ${q(o.ship.tn)}, ${q(o.ship.st)}, 'NikiMart Freight', ${q(o.ship.from)}, ${q(o.ship.to)}, now() + interval '2 days', now(), now(), ${q(o.id)}, 'usr-freight');`,
  );
}
out.push("");
out.push("COMMIT;");
out.push("");

const outPath = path.join(process.cwd(), "nikimart-neon-setup.sql");
writeFileSync(outPath, out.join("\n"));
console.log(`Wrote ${outPath} (${out.length} lines)`);
