-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "heightCm" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "lengthCm" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "widthCm" DOUBLE PRECISION NOT NULL DEFAULT 0;
